export const CATEGORIES = [
  'Food & Dining',
  'Transport',
  'Shopping',
  'Entertainment',
  'Bills & Utilities',
  'Health',
  'Education',
  'Travel',
  'Subscriptions',
  'Salary',
  'Freelance',
  'Investment',
  'Other',
] as const;

export type Category = typeof CATEGORIES[number];

const CATEGORY_KEYWORDS: Record<string, Category> = {
  swiggy: 'Food & Dining',
  zomato: 'Food & Dining',
  restaurant: 'Food & Dining',
  food: 'Food & Dining',
  lunch: 'Food & Dining',
  dinner: 'Food & Dining',
  coffee: 'Food & Dining',
  grocery: 'Food & Dining',
  uber: 'Transport',
  ola: 'Transport',
  cab: 'Transport',
  fuel: 'Transport',
  petrol: 'Transport',
  metro: 'Transport',
  bus: 'Transport',
  amazon: 'Shopping',
  flipkart: 'Shopping',
  shopping: 'Shopping',
  clothes: 'Shopping',
  netflix: 'Subscriptions',
  spotify: 'Subscriptions',
  subscription: 'Subscriptions',
  youtube: 'Subscriptions',
  premium: 'Subscriptions',
  electricity: 'Bills & Utilities',
  water: 'Bills & Utilities',
  internet: 'Bills & Utilities',
  wifi: 'Bills & Utilities',
  phone: 'Bills & Utilities',
  rent: 'Bills & Utilities',
  recharge: 'Bills & Utilities',
  movie: 'Entertainment',
  game: 'Entertainment',
  concert: 'Entertainment',
  doctor: 'Health',
  medicine: 'Health',
  hospital: 'Health',
  pharmacy: 'Health',
  gym: 'Health',
  salary: 'Salary',
  paycheck: 'Salary',
  freelance: 'Freelance',
  project: 'Freelance',
  course: 'Education',
  book: 'Education',
  tuition: 'Education',
  flight: 'Travel',
  hotel: 'Travel',
  trip: 'Travel',
  vacation: 'Travel',
  invest: 'Investment',
  stock: 'Investment',
  mutual: 'Investment',
  dividend: 'Investment',
};

export function autoDetectCategory(description: string): Category {
  const lower = description.toLowerCase();
  for (const [keyword, category] of Object.entries(CATEGORY_KEYWORDS)) {
    if (lower.includes(keyword)) return category;
  }
  return 'Other';
}

export const CATEGORY_COLORS: Record<string, string> = {
  'Food & Dining': '#FF6B6B',
  'Transport': '#4ECDC4',
  'Shopping': '#FFE66D',
  'Entertainment': '#A06CD5',
  'Bills & Utilities': '#6C9BCF',
  'Health': '#2ECC71',
  'Education': '#3498DB',
  'Travel': '#E67E22',
  'Subscriptions': '#E74C3C',
  'Salary': '#27AE60',
  'Freelance': '#16A085',
  'Investment': '#8E44AD',
  'Other': '#95A5A6',
};

export const CATEGORY_ICONS: Record<string, string> = {
  'Food & Dining': '🍕',
  'Transport': '🚗',
  'Shopping': '🛍️',
  'Entertainment': '🎬',
  'Bills & Utilities': '💡',
  'Health': '🏥',
  'Education': '📚',
  'Travel': '✈️',
  'Subscriptions': '🔄',
  'Salary': '💰',
  'Freelance': '💼',
  'Investment': '📈',
  'Other': '📦',
};
